name: td_classifier
channels:
  - anaconda
  - defaults
dependencies:
  - pip=21.1.1
  - flask=1.1.2
  - flask-cors=3.0.10
  - gitpython=3.1.17
  - numpy=1.19.2
  - pandas=1.1.5
  - python=3.6.13
  - requests=2.25.1
  - scikit-learn=0.23.2
  - waitress=2.0.0
  - pip:
    - lizard==1.17.7
    - pydriller==2.0
